# Generated by Django 6.0.3 on 2026-04-30 05:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_announcementmerk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnnouncementMerk',
            new_name='AnnouncementMark',
        ),
    ]
