# Generated by Django 6.0.3 on 2026-04-30 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_announcementmerk_announcementmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementmark',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='main.announcement'),
        ),
    ]
