# Generated by Django 6.0.3 on 2026-04-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_announcementmark_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcementmark',
            old_name='book',
            new_name='re_announcement',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='book',
            new_name='re_announcement',
        ),
    ]
