# Generated by Django 6.0.3 on 2026-05-02 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_book_announcementmark_re_announcement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('noactive', 'Faol emas')], default='active', max_length=30)),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='main.announcement')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.ManyToManyField(related_name='announcements', to='main.author'),
        ),
    ]
