# Generated by Django 6.0.3 on 2026-05-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_author_announcementstatus_announcement_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
