# Generated by Django 6.0.3 on 2026-05-07 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_author_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-create_announcement',), 'verbose_name': "E'lon", 'verbose_name_plural': "E'lonlar"},
        ),
        migrations.AlterModelOptions(
            name='announcementmark',
            options={'verbose_name': 'Saralnganlar'},
        ),
        migrations.AlterModelOptions(
            name='announcementstatus',
            options={'verbose_name': 'Holati', 'verbose_name_plural': 'Holati'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Elon beruvchi', 'verbose_name_plural': 'Elon beruvchilar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Fikr', 'verbose_name_plural': 'Fikrlar'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.ManyToManyField(related_name='announcements', to='main.author', verbose_name='Elon egasi'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name="Bo'limi"),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='name',
            field=models.CharField(max_length=150, verbose_name="E'lon nomi"),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='number',
            field=models.CharField(max_length=15, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='announcementstatus',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('noactive', 'Faol emas')], default='active', max_length=30, verbose_name='Elon holati'),
        ),
        migrations.AlterField(
            model_name='author',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name="To'liq nomi"),
        ),
        migrations.AlterField(
            model_name='author',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Matn'),
        ),
    ]
